Feature azureblob discovery
intrigueio/intrigue-core pull request #194
Opened 2020-10-01 00:34 UTC by AnasBensalah

2020-11-16 22:26 UTC, shpendk requested changes
Some changes needed before we can merge this one. Also, there is a file named `search_azure_blob_test.rb`. Please remove it since it seems to be a test file.

2020-11-16 22:26 UTC, shpendk commented on lib/issues/azure_blob_exposed_files.rb
> +      added: "2020-01-01",
Date is wrong and should be corrected

2020-11-16 22:26 UTC, shpendk commented on lib/issues/azure_blob_exposed_files.rb
> +      status: "confirmed",
Suggest to change it to potential. Files may be public by design.

2020-11-16 22:26 UTC, shpendk commented on lib/issues/azure_blob_open_publicly.rb
> +      added: "2020-01-01",
Date is wrong and should be corrected

2020-11-16 22:26 UTC, shpendk commented on lib/issues/azure_blob_open_publicly.rb
> +      status: "confirmed",
Suggest to change it to potential. Blob may be open to public by design

2020-11-16 22:26 UTC, shpendk commented on lib/tasks/search_azure_blob.rb
> +      account_name = account_name.split('.', 0)
The split actually returns an array. I tested it with a domain and it didn't seem to work, so this looks like a bug.

2020-11-24 22:19 UTC, AnasBensalah commented on lib/tasks/search_azure_blob.rb
> +      account_name = account_name.split('.', 0)
fixed

2020-11-25 00:00 UTC, AnasBensalah commented on lib/issues/azure_blob_open_publicly.rb
> +      added: "2020-01-01",
Date corrected

2020-11-25 00:00 UTC, AnasBensalah commented on lib/issues/azure_blob_open_publicly.rb
> +      status: "confirmed",
change made

2020-11-25 00:03 UTC, AnasBensalah commented on lib/issues/azure_blob_exposed_files.rb
> +      status: "confirmed",
change made

2020-11-25 23:31 UTC, closed without merging