F5 Big IP Cookie Decoder
intrigueio/intrigue-core pull request #313
Opened 2021-03-25 00:53 UTC by m-q-t

Hi team,

Please find attached the F5 Big IP Cookie Decoder task.

**Behavior**:
The way the task works is by sending 10 requests to the application and decodes the cookie of each request. The amount of requests was adopted from the MSF Module and is done so because each time the cookie is decoded a different Internal IP Address can be returned. The caveat is that if the task doesn't successfully decode a cookie by the second request, it ceases firing off requests in order to suppress the noisiness. 

In the scenario where a F5 Big IP Cookie is successfully decoded; it will clear out the duplicate IP Addresses and create an issue which will display all the leaked pool names, internal Ip Addresses and ports. A new entity will be created per IP Address as well.

![image](https://user-images.githubusercontent.com/13172047/112402422-bea91800-8cc9-11eb-8ebc-0abdfe47fbf4.png)

![image](https://user-images.githubusercontent.com/13172047/112402399-b3ee8300-8cc9-11eb-93c6-c606f50730d9.png)

Best regards,
Maxim

2021-03-26 19:07 UTC, shpendk requested changes
See the inline comment

2021-03-26 19:07 UTC, shpendk commented on lib/tasks/f5_bigip_cookie_decoder.rb
> +          ip_address = nil
If we land in the else branch, we should note that this is not an issue and not raise the issue

2021-04-04 00:03 UTC, m-q-t commented
@shpendk 

Thanks for looking into this + catching the bug. Should be fixed with the latest commit.

Best, 
Maxim

2021-04-04 20:21 UTC, jcran commented
Great work on this, merging.

2021-04-04 20:21 UTC, merged