Multiple Ruclei Checks
intrigueio/intrigue-core pull request #316
Opened 2021-03-30 22:43 UTC by jen140

Added the following ruclei checks:
drupal_cve_2019_6340
jfrog_artifactory_cve_2019_9733
jira_cve_2019_8442
jira_cve_2019_8449
total_js_cve_2019_8903
w3_total_cache_cve_2019_6715

2021-04-01 14:56 UTC, shpendk requested changes
Need some changes mostly for consistency sake. Otherwise really good job mate!

2021-04-01 14:56 UTC, shpendk commented on lib/checks/drupal_cve_2019_6340.rb
> +          pretty_name: "Drupal RCE with CVE-2019-6340.",
Lets write out `Remote Code Execution` and include the CVE in parenthesis. Example:
```
"Citrix ShareFile StorageZones Unauthenticated Arbitrary File Read Vulnerability (CVE-2020-8982)
```

2021-04-01 14:56 UTC, shpendk commented on lib/checks/drupal_cve_2019_6340.rb
> +          authors: ["jen140"]
include original author of poc and author of nuclei template

2021-04-01 14:56 UTC, shpendk commented on lib/checks/jfrog_artifactory_cve_2019_9733.rb
> +          pretty_name: "Jfrog Artifactory unauthenticated admin password reset CVE-2019-9733",
All words should begin with capital letter

2021-04-01 14:56 UTC, shpendk commented on lib/checks/jfrog_artifactory_cve_2019_9733.rb
> +          authors: ["jen140"]
include original author of poc and author of nuclei template

2021-04-01 14:56 UTC, shpendk commented on lib/checks/jira_cve_2019_8442.rb
> +          pretty_name: "Jira Server META-INF directory exposure with CVE-2019-8442.",
All words should begin with capital letter

2021-04-01 14:56 UTC, shpendk commented on lib/checks/jira_cve_2019_8442.rb
> +            { type: "description", uri: "https://nvd.nist.gov/vuln/detail/CVE-2019-8442" }
can we find more references? There should be a description of Atlassian for this issue, and maybe we can find a poc/exploit?

2021-04-01 14:56 UTC, shpendk commented on lib/checks/jfrog_artifactory_cve_2019_9733.rb
> +            { type: "POC", uri: "https://packetstormsecurity.com/files/152172/JFrog-Artifactory-Administrator-Authentication-Bypass.html" }
change type from `POC` to `exploit`

2021-04-01 14:56 UTC, shpendk commented on lib/checks/jira_cve_2019_8449.rb
> +          pretty_name: "Jira username enumeration vulnerability with CVE-2019-8449.",
All words should begin with capital letter

2021-04-01 14:56 UTC, shpendk commented on lib/checks/jira_cve_2019_8449.rb
> +          severity: 1,
This does not sound like a severity 1 issue to me

2021-04-01 14:56 UTC, shpendk commented on lib/checks/jira_cve_2019_8449.rb
> +            { type: "POC", uri: "https://packetstormsecurity.com/files/156172/Jira-8.3.4-Information-Disclosure.html" }
change type from POC to exploit

2021-04-01 14:56 UTC, shpendk commented on lib/checks/jira_cve_2019_8442.rb
> +          authors: ["jen140"]
include original author of poc and author of nuclei template

2021-04-01 14:56 UTC, shpendk commented on lib/checks/jira_cve_2019_8449.rb
> +          authors: ["jen140"]
include original author of poc and author of nuclei template

2021-04-01 14:56 UTC, shpendk commented on lib/checks/total_js_cve_2019_8903.rb
> +          authors: ["jen140"]
include original author of poc and author of nuclei template

2021-04-01 14:56 UTC, shpendk commented on lib/checks/total_js_cve_2019_8903.rb
> +          pretty_name: "Total.js path traversal vulnerability with CVE-2019-8903.",
All words should begin with capital letter and the CVE number should be in parenthesis

2021-04-01 14:56 UTC, shpendk commented on lib/checks/total_js_cve_2019_8903.rb
> +          description: "index.js in Total.js Platform before 3.2.3 allows path traversal.",
Maybe we can find a longer more descriptive description?

2021-04-01 14:56 UTC, shpendk commented on lib/checks/total_js_cve_2019_8903.rb
> +            { type: "description", uri: "https://nvd.nist.gov/vuln/detail/CVE-2019-8903" }
can we find more references? There should be a description of the vendor for this issue, and maybe we can find a poc/exploit link

2021-04-01 14:56 UTC, shpendk commented on lib/checks/w3_total_cache_cve_2019_6715.rb
> +          authors: ["jen140"]
include original author of poc and author of nuclei template

2021-04-01 14:56 UTC, shpendk commented on lib/checks/w3_total_cache_cve_2019_6715.rb
> +          pretty_name: "W3 Total Cache Wordpress Plugin Arbitrary file read with CVE-2019-6715.",
All words should begin with capital letter and the CVE number should be in parenthesis

2021-04-01 14:56 UTC, shpendk commented on lib/checks/w3_total_cache_cve_2019_6715.rb
> +            { type: "POC", uri: "https://packetstormsecurity.com/files/160674/WordPress-W3-Total-Cache-0.9.3-File-Read-Directory-Traversal.html" }
change type from POC to exploit

2021-04-02 13:24 UTC, jen140 commented
Fixed everything as requested (except total.js description).

2021-04-02 20:01 UTC, shpendk approved these changes
Looks good now, thanks again

2021-04-02 20:02 UTC, merged