updating search spyse cert task with API v4
intrigueio/intrigue-core pull request #353
Opened 2021-06-14 22:12 UTC by AnasBensalah

Updating search spyse cert task with recent Spyse API version v4 and adding new findings to the task:

![image](https://user-images.githubusercontent.com/35723779/121966011-d4c4f280-cd65-11eb-8418-1ace2820ed2e.png)
![image](https://user-images.githubusercontent.com/35723779/121966036-dc849700-cd65-11eb-9e3d-069c626dde0c.png)

2021-06-20 20:19 UTC, shpendk requested changes
See inline comments

2021-06-20 20:19 UTC, shpendk commented on lib/tasks/search_spyse_cert.rb
> +          description: 'This task hits Spyse API for discovring domains registered with the same certificate',
typo in "discovering"

2021-06-20 20:19 UTC, shpendk commented on lib/issues/wildcard_certificate.rb
> +          severity: 4,
please change severity to 5

2021-06-20 20:19 UTC, shpendk commented on lib/tasks/search_spyse_cert.rb
> +            _create_linked_issue('wildcard_certificate', {
How do we know this is a wildcard certificate?

2021-06-29 13:39 UTC, shpendk commented
Changes as per our discussion:
The task itself should not create any issues. It should only collect new entities and create those. The issues `expired_cert` and `almost_expired_cert` are handled in enrichment. The wildcard certificate check should be moved to enrichment too, and verified on the certificate itself.

2021-07-16 21:40 UTC, shpendk requested changes
Running this against `amazon.com` returns the following error:
```
23:36:07 worker.1 | 2021-07-16T21:36:07.927Z pid=96853 tid=p49 WARN: NoMethodError: undefined method `[]' for nil:NilClass
23:36:07 worker.1 | 2021-07-16T21:36:07.927Z pid=96853 tid=p49 WARN: intrigue-core/lib/tasks/search_spyse_cert.rb:40:in `run'
23:36:07 worker.1 | intrigue-core/lib/tasks/base.rb:160:in `perform'

```

I also tested against an actual SslCertificate entity (which came from `uri_gather_ssl_certificate` task, and the error appears again. We need to do better error handling before we can merge this code.

2021-08-05 14:23 UTC, shpendk commented
Have yet to find a time when the api key is not over quota to test this task.

2021-08-05 23:23 UTC, AnasBensalah reviewed
> Have yet to find a time when the api key is not over quota to test this task.

regex added and tested

2021-09-08 21:50 UTC, shpendk commented
@AnasBensalah Can you please resolve the conflict and confirm this task is now working as expected? Thanks

2021-09-09 12:04 UTC, AnasBensalah commented
> @AnasBensalah Can you please resolve the conflict and confirm this task is now working as expected? Thanks

@shpendk it should work fine but unfortunately, I can't test it since Spyse abandoned the free trial.

2021-09-30 18:36 UTC, merged