Adds IPData geolocation
intrigueio/intrigue-core pull request #392
Opened 2021-08-09 20:18 UTC by duartemateus

2021-08-10 22:05 UTC, shpendk requested changes
Looks good to me for the one inline issue, and regarding the file `data/web_accounts_list/GeoLite2-City.mmdb` I was wondering if this is still needed? If not, we should remove it

2021-08-10 22:05 UTC, shpendk commented on config/config.json.default
> +    "geolocation_api_key": {
I'd rename this to `ipdata_api_key` just so we know the provider

2021-08-10 22:23 UTC, duartemateus commented on config/config.json.default
> +    "geolocation_api_key": {
will do, wasn't too sure if we wanted to "obfuscate" the provider we were using!

2021-08-10 22:28 UTC, duartemateus commented
> Looks good to me for the one inline issue, and regarding the file `data/web_accounts_list/GeoLite2-City.mmdb` I was wondering if this is still needed? If not, we should remove it

Think we can bin that I'll ping you just to do some testing after removal as I have encountered some issues on my side when attempting to get rid of all usages of maxmind, including the Gem and so on.

2021-08-11 19:32 UTC, shpendk approved these changes
looking good.

2021-08-11 19:33 UTC, merged